pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
def targetVersion = providers.gradleProperty('targetVersion').getOrNull()

if (targetVersion == null || targetVersion == 'v1_21_4') {
    include 'v1_21_4'
}

if (targetVersion == null || targetVersion == 'v1_21_11') {
    include ':v1_21_11'
    project(':v1_21_11').projectDir = file('v1_21_11')
}
